### ISSUE TITLE
Test full round trip of random agent

### ISSUE THREAD

**Issue by masonlr** [rangl-labs/netzerotc#104]
The latest EvalAI platform and challenge environment are live at:

* http://challenges.rangl.org
* http://submissions.rangl.org

We need to test a round trip submission.

The steps involved are:

1. Register for http://challenges.rangl.org and participate in the challenge.

2. Submit an agent using:

```shell
git clone https://github.com/rangl-labs/netzerotc.git

# build the agent image
cd netzerotc/random_agent_submission
make build

# submit the agent image
evalai host -sh http://submissions.rangl.org
evalai login
evalai push submission:v0.1.0 --phase nztc-open-loop-1
```

**Comment by masonlr** [comment]
Any tweaks to the problem can be captured in PR #103

**Comment by tomaszkosmala** [comment]
I completed the roundtrip
