### ISSUE TITLE
Test full round trip of RL agent

### ISSUE THREAD

**Issue by tomaszkosmala** [rangl-labs/netzerotc#105]
The latest EvalAI platform and challenge environment are live at:

* http://challenges.rangl.org
* http://submissions.rangl.org

We need to test a round trip submission.

The steps involved are:

1. Register for http://challenges.rangl.org and participate in the challenge.
2. Test the containerised submission locally using the instructions here: https://github.com/rangl-labs/netzerotc/tree/main/random_agent_submission#local-testing

3. Submit an agent using the code from the `meaningful_agent` branch:

```shell
git clone https://github.com/rangl-labs/netzerotc.git
git checkout meaningful_agent

# build the agent image
cd netzerotc/meaningful_agent_submission
make build

# submit the agent image
evalai host -sh http://submissions.rangl.org
evalai login
evalai push submission:v0.1.0 --phase nztc-open-loop-1
```

**Comment by masonlr** [comment]
This has been completed.
