### ISSUE TITLE
Changelogs for 1-Year shifting/acceleration and sensitivities calculation

### ISSUE THREAD

**Issue by jia-chenhua** [rangl-labs/netzerotc#12]
1. Changes made to "Pathways to Net Zero - 1-Year Shifting.xlsx" (compared to the original "Pathways to Net Zero.xlsx"): for spreadsheets BREEZE, GALE, STORM, the following cells' formulae are changed:

H26 =H25 * (1 + RRI(COUNT($B$26:$B$55), H$25,H$55))
is changed to 
H26 =H25 * (1 + RRI(COUNT($B$26:$B$55), H$25,H$55)) * (1 + RRI(COUNT($B$26:$B$55), H$25,H$55))
(double deployment for year 2021; all following years will be changed accordingly because H[n]=H[n-1] * (1 + RRI(COUNT($B$26:$B$55), H$25,H$55)) for all following n's)

P36 =P35 * (1 + RRI(COUNT($B$36:$B$55), P$35,P$55))
is changed to 
P36 =P35 * (1 + RRI(COUNT($B$36:$B$55), P$35,P$55)) * (1 + RRI(COUNT($B$36:$B$55), P$35,P$55))
(double deployment for year 2031; all following years will be changed accordingly because P[n]=P[n-1] * (1 + RRI(COUNT($B$26:$B$55), H$25,H$55)) for all following n's)

X26:X54 =$X$55*Deployment!D3:D31
is changed to
X26:X54 =$X$55*Deployment!D4:D32
(shifting deployment rate from D3:D31 to D4:D32 from the "Deployment" spreadsheet)

Y26:Y54=$Y$55 * Deployment!D3:D31
is changed to
Y26:Y54=$Y$55 * Deployment!D4:D32
(shifting deployment rate from D3:D31 to D4:D32 from the "Deployment" spreadsheet)

(after the above modifications, the original "Pathways to Net Zero.xlsx" is saved as "Pathways to Net Zero - 1-Year Shifting.xlsx")

2. From the original "Pathways to Net Zero.xlsx" and the 1-Year shifted "Pathways to Net Zero - 1-Year Shifting.xlsx", copy the "Outputs" spreadsheet and save as "Pathways to Net Zero - Original - Outputs with Total capex opex revenue.xlsx" and "Pathways to Net Zero - 1-Year Shifting - Outputs with Total capex opex revenue.xlsx", and then in both newly saved spreadsheet, add new rows in grey to calculate total capex, opex, revenue among all technologies, for all 3 scenarios Breeze, Gale, Storm. And then copy only the key outputs values in grey and save them as "Pathways to Net Zero - Original - Outputs - Key outputs Only.xlsx" and "Pathways to Net Zero - 1-Year Shifting - Outputs - Key outputs Only.xlsx", which contain less enough information to be uploaded to GitHub netzerotc/environment/sensitivities/. Then extract only the summed total capex, total opex, total revenue, for all 3 scenarios, and save as "Pathways to Net Zero - Original - Total capex.xlsx", "Pathways to Net Zero - Original - Total revenue.xlsx", "Pathways to Net Zero - Original - Total opex.xlsx" for original, and save as "Pathways to Net Zero - 1-Year Shifting - Total capex.xlsx", "Pathways to Net Zero - 1-Year Shifting - Total revenue.xlsx", "Pathways to Net Zero - 1-Year Shifting - Total opex.xlsx" for 1-Year Shifting. Again, they are safe to be uploaded to GitHub.

3. Copy the key outputs values in grey in "Pathways to Net Zero - 1-Year Shifting.xlsx" - "Outputs" to "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL.xlsx" - "Pathway Inputs", switch to "Master Sheet" spreadsheet within the workbook, press F9 to update, save it as "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL - 1-Year Shifting F9 Update.xlsx", and then copy the rows containing total jobs (with and without induced) for all 3 scenarios to a new spreadsheet and save it as "IEV - 1-Year Shifting - Total Jobs.xlsx" (without induced jobs) and/or "IEV - 1-Year Shifting - Total Jobs Including Induced.xlsx" (with induced jobs). Switch to the original "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL.xlsx" and copy the original total jobs with and without induced to new spreadsheets and save as "IEV - Original - Total Jobs.xlsx" and "IEV - Original - Total Jobs Including Induced.xlsx". These 4 newly saved spreadsheets contain less enough information to be uploaded to GitHub netzerotc/environment/sensitivities/.

4. Adding total economic impact: in both "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL.xlsx" and "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL - 1-Year Shifting F9 Update.xlsx", add new rows to sum over economic impacts of all different technologies (in grey background only: without doubling counting the offshore wind to power/green H2 with the total offshore wind), and then save as "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL Original - Adding Total Economic Impact.xlsx" and "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL 1-Year Shifting - Adding Total Economic Impact.xlsx". Then similar to step 3 for total jobs above, copy the total economic impacts for 3 scenarios for original and 1-Year Shifting to new spreadsheets and save as "IEV - Original - Total Economic Impact.xlsx" and "IEV - 1-Year Shifting - Total Economic Impact.xlsx". Again, these 2 spreadsheets contain no sensitive information and can be uploaded to GitHub.

5. For carbon emissions cost/rewards, in terms of carbon tax for uncaptured carbon: from the spreadsheet "CCUS" of both "Pathways to Net Zero - 1-Year Shifting.xlsx" and "Pathways to Net Zero - Original.xlsx", copy row 57, 68, 79 of carbon tax for uncaptured carbon for 3 scenarios to new spreadsheets and save as "Pathways to Net Zero - Original - Carbon tax for uncaptured carbon.xlsx" and "Pathways to Net Zero - 1-Year Shifting - Carbon tax for uncaptured carbon.xlsx". These 2 newly saved spreadsheets contain no sensitive information and can be uploaded to GitHub.

6. Sensitivities calculations for total capex, total opex, total revenue, total jobs, emissions, total economic impacts:

For all except capex, sensitivities ratios are calculated by 1-Year shifted spreadsheet's n-th year's value divided by original spreadsheet's (n+1)-th year's value, for example, using "Pathways to Net Zero - Original - Total opex.xlsx" and "Pathways to Net Zero - 1-Year Shifting - Total opex.xlsx", 2022's value in 1-Year shifted spreadsheet is divided by 2023's value in original spreadsheet, and this is the sensitivity ratio for year 2022, and these are saved as "Pathways to Net Zero - Total opex Sensitivity Ratio for 1-Year Shifting.csv". 

For total capex, sensitivities ratios are initially calculated as above, but then for the boundary year 2021, the 2021's value in 1-Year shifted spreadsheet is subtracted by 2021's value in the original spreadsheet, and then divided by 2022's value in original spreadsheet.

In summary:

Pathways to Net Zero - Total capex Sensitivity Ratio for 1-Year Shifting.csv
is calculated from:
Pathways to Net Zero - 1-Year Shifting - Total capex.xlsx
Pathways to Net Zero - Original - Total capex.xlsx

Pathways to Net Zero - Total opex Sensitivity Ratio for 1-Year Shifting.csv
is calculated from:
Pathways to Net Zero - 1-Year Shifting - Total opex.xlsx
Pathways to Net Zero - Original - Total opex.xlsx

Pathways to Net Zero - Total revenue Sensitivity Ratio for 1-Year Shifting.csv
is calculated from:
Pathways to Net Zero - Original - Total revenue.xlsx
Pathways to Net Zero - 1-Year Shifting - Total revenue.xlsx

IEV - Total Economic Impact Sensitivity Ratio for 1-Year Shifting.csv
is calculated from:
IEV - Original - Total Economic Impact.xlsx
IEV - 1-Year Shifting - Total Economic Impact.xlsx

Pathways to Net Zero - Total emissions (uncaptured carbon tax) Sensitivity Ratio for 1-Year Shifting.csv
is calculated from:
Pathways to Net Zero - Original - Carbon tax for uncaptured carbon.xlsx
Pathways to Net Zero - 1-Year Shifting - Carbon tax for uncaptured carbon.xlsx

IEV - Total Jobs Sensitivity Ratio for 1-Year Shifting.csv
is calculated from:
IEV - 1-Year Shifting - Total Jobs.xlsx
IEV - Original - Total Jobs.xlsx

IEV - Total Jobs Including Induced Sensitivity Ratio for 1-Year Shifting.csv
is calculated from:
IEV - Original - Total Jobs Including Induced.xlsx
IEV - 1-Year Shifting - Total Jobs Including Induced.xlsx

All these files contain no sensitive information and can be uploaded to GitHub.

7. Added relevant codes in env.py to read the original 6 rewards values into the Parameters.IEV_Rewards from the following 6 files:
Pathways to Net Zero - Original - Total capex.xlsx
Pathways to Net Zero - Original - Total opex.xlsx
Pathways to Net Zero - Original - Total revenue.xlsx
IEV - Original - Total Economic Impact.xlsx
Pathways to Net Zero - Original - Carbon tax for uncaptured carbon.xlsx
IEV - Original - Total Jobs.xlsx (or IEV - Original - Total Jobs Including Induced.xlsx)
Also added relevant codes in env.py to read the sensitivity ratios into the Parameters.IEV_RewardSensitivities from the following 6 files:
Pathways to Net Zero - Total capex Sensitivity Ratio for 1-Year Shifting.csv
Pathways to Net Zero - Total opex Sensitivity Ratio for 1-Year Shifting.csv
Pathways to Net Zero - Total revenue Sensitivity Ratio for 1-Year Shifting.csv
IEV - Total Economic Impact Sensitivity Ratio for 1-Year Shifting.csv
Pathways to Net Zero - Total emissions (uncaptured carbon tax) Sensitivity Ratio for 1-Year Shifting.csv
IEV - Total Jobs Sensitivity Ratio for 1-Year Shifting.csv (or IEV - Total Jobs Including Induced Sensitivity Ratio for 1-Year Shifting.csv)

Potential issues and questions:

The total capex is the sum of capex of offshore wind, green hydrogen, blue hydrogen, oil & gass, CCUS. When shifting the deployment by 1 year, the capex of green and blue hydrogen has the correct boundary behavior: 2021's new capex is close to 2021+2022 old capex, but for other technologies' capex, this is not true as we are not directly accelerating the deployment of them. When adding them together to get the total capex, it might not be reasonable to calculate the boundary year as above. Instead, it might be more reasonable to calculate them separately: non-accelerating techs' capex boundary calculated as without boundary using 2021's new, accelerating techs' capex boundary calculated by (2021's new - 2021's old), then sum these together, and then divided by 2022's old total capex. However, things will get even more complicated because starting from 2031, the deployment of "offshore wind capacity in GW" will start to accelerate by 1 year at the beginning, so this special treatment of boundary may have to do again for 2031.

**Comment by jia-chenhua** [comment]
Changelogs for approximating partial derivatives of jobs & economic impact w.r.t. capex using the IEV economic model:

1. In the original "Pathways to Net Zero.xlsx", duplicate the "Output" spreadsheet and rename it as "Outputs - capex+Delta100", and for all 3 scenarios, for green & hydrogen capex, manually add 100 to the original numbers starting from 2021, and for offshore wind capex, manually add 100 to the original numbers starting from 2031. This was done by first copying and pasting the *links* of the original numbers to a blank row, editing the formula by adding +100, dragging the cell to auto fill the +100 formula, and finally copying and pasting the *values* back to the original cells, and then delete the contents in the originally blank cells.

2. Save this modified spreadsheet as "Pathways to Net Zero - Original with new sheet Outputs - capex+Delta100.xlsx", and same as Step 3 & 4 in the post/comment above, copy key outputs values in grey in the Delta=100 applied spreadsheet "Outputs - capex+Delta100" above to the IEV model's workbook's "Pathway Inputs" spreadsheet, and then press F9 to update the total jobs and total economic impact in the "Master Sheet", and then save the updated IEV model workbook as "OGTC-ORE Catapult IEV pathways economic model v01.06 FINAL capex+Delta100 - Adding Total Economic Impact.xlsx". Both this workbook xlsx and the "Pathways to Net Zero - Original with new sheet Outputs - capex+Delta100.xlsx" have been uploaded to MS Teams.

3. Same as Step 3 & 4 in the post/comment above, extract the updated total jobs and total economic impact to new spreadsheets, and save them as "IEV - capex+Delta100 - Total Jobs.xlsx" and "IEV - capex+Delta100 - Total Economic Impact.xlsx", respectively. Similar to the post/comment above, these 2 saved spreadsheets contain no sensitive information and can be uploaded to GitHub.

4. Calculating/approximating the partial derivatives (details can be found in https://github.com/rangl-labs/netzerotc/issues/13#issuecomment-915383934) by $`\frac{ r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}}_k+\Delta, \chi^{\mathrm{op}}_k, r^{\mathrm{rev}}_k) - r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}}_k, \chi^{\mathrm{op}}_k, r^{\mathrm{rev}}_k) }{ \sum \Delta }`$, where the new $`r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}}_k+\Delta, \chi^{\mathrm{op}}_k, r^{\mathrm{rev}}_k)`$ are saved in "IEV - capex+Delta100 - Total Jobs.xlsx" and "IEV - capex+Delta100 - Total Economic Impact.xlsx", respectively, and the total capex change is $`\sum \Delta=200`$ in the denominator from 2021, and $`\sum \Delta=300`$ from 2031. The calculated derivatives are saved in csv files "IEV - Total Jobs Derivative for capex+Delta100.csv" and "IEV - Total Economic Impact Derivative for capex+Delta100.csv", and they are uploaded to both MS Teams/General/Sensitivities Calculation/ and https://github.com/rangl-labs/netzerotc/tree/master/environment/sensitivities as they don't contain any sensitive information.

5. Similar to Step 7 in the post/comment above, added new lines to the `env.py` and `test_reference_environment.py` to read the saved csv and xlsx files to testing and actual calculation.

**Comment by moriartyjm** [comment]
This approach is on hold, as we have successfully compiled the spreadsheets to Python
