### ISSUE TITLE
Mathematical Notations for Clarifying the Calculations of Time and Size Sensitivity Ratios

### ISSUE THREAD

**Issue by jia-chenhua** [rangl-labs/netzerotc#13]
### **Note**: Please first install https://github.com/nschloe/xdoc in a Google Chrome/[Chromium-based web browser](https://en.wikipedia.org/wiki/Chromium_(web_browser)#Browsers_based_on_Chromium), and see if this equation: $`e^{i \pi} + 1 = 0`$ is rendered correctly.

Suppose that a reward has been shifted from year $`k`$ to year $`j\leq k-1`$. The new reward is

```math
\left(\prod_{i=j}^{k-1} s_i \right) r_k,
```
where $`s_i:=\frac{\widetilde{r}_{i}}{r_{i+1}}`$, and
$`r_i:=`$ oiginal cost for year $`i`$
$`\widetilde{r}_i:=`$ 1-year shifted cost for year $`i`$.
(side note: it is assumed that $`s_{i-2}s_{i-1} = \frac{\widetilde{r}_{i-2}}{r_{i-1}} \frac{\widetilde{r}_{i-1}}{r_i}`$ should approximate the ratio $`\frac{\widetilde{r}_{i-2}}{r_i}`$ **to the lowest order**.)

Example:
To shift by one year:
```math
\left(\prod_{i=k-1}^{k-1} s_i \right) r_k = s_{k-1} r_k = \frac{\widetilde{r}_{k-1}}{r_k} r_k = \widetilde{r}_{k-1}.
```

**Update**: the index for sensitivity ratio is changed from $`s_i:=\frac{\widetilde{r}_{i-1}}{r_{i}}`$ to $`s_i:=\frac{\widetilde{r}_{i}}{r_{i+1}}`$, in order to be more consistent with any loop index `sensitivityYear` in `env.py`, e.g., in https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L133 and in https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L155, where the `sensitivityYear` could only reach the `stop-1` of `np.arange(start, stop)`, and the `sensitivityYear`-th year's sensitivity stored in the arrays and also the xlsx files is the ratio of `sensitivityYear`-th year to `(sensitivityYear+1)`-th year.

**Comment by moriartyjm** [comment]
Great, thanks Jia-Chen -- also, for adding equations to our Github! So, the above could be called 'time sensitivities' because they allow us to bring rewards earlier in time.

I believe that we should also deal with capex using sensitivities. (This would also have the advantage of consistency with the above). Instead of shifting the deployment in time, we would shift the capex in **size**. So the algorithm would be:

1. In the economic model spreadsheet, on the 'Pathways inputs' tab, add an equal increment (eg. Delta = 100) to all capex numbers
2. Calculate the 'Capex sensitivity ratios' for total economic impact and for jobs
3. In the environment, when there is an acceleration in year k, multiply the reward (ie either total economic impact or jobs) by (increase in capex in year k due to acceleration)/Delta * Capex sensitivity ratio for year k for that reward type (ie either total economic impact or jobs)

**Comment by jia-chenhua** [comment]
So that 'size sensitivity' calculation will be:

1. In the 'OGTC-ORE Catapult IEV pathways economic model' spreadsheet, on the 'Pathways inputs' tab, add an equal increment (eg. $`\Delta = 100`$) to all capex numbers;
2. Calculate the 'Capex sensitivity ratios' for total economic impact and for jobs, that is $`\frac{\widetilde{r}_{i}}{r_i}`$, where $`r_i`$ is the original total economic impact or jobs for year $`i`$, and $`\widetilde{r}_{i}`$ is the total economic impact or jobs when all capex numbers in the 'Pathways inputs' tab of 'OGTC-ORE Catapult IEV pathways economic model' workbook is increased by $`\Delta = 100`$;
3. In the environment, when there is an acceleration in year $`k`$, $`r_k \times \frac{\widetilde{r^{\mathrm{(capex)}}}_{k}}{\Delta} \times $`\frac{\widetilde{r}_{i}}{r_i}`$, where $`r`$ is either total economic impact or jobs, and $`\widetilde{r^{\mathrm{(capex)}}}_{k}`$ is the size-increased new capex of year $`k`$.

The above is my understanding, so @moriartyjm , please correct me if there is any misunderstanding. Thanks!

**Comment by jia-chenhua** [comment]
(Notations: $`r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}_k, \chi^{\mathrm{cap}_k, r^{\mathrm{rev}_k)`$)

**Comment by moriartyjm** [comment]
Many thanks Jia-Chen, this is great progress. Note that whenever there is an acceleration by one year, we need to apply two operations: the capex derivative _and_  the time sensitivity. So if there is a double deployment in year k, we need to 
1. Account for the increased capex in year k by applying the capex derivative for year k (as you have described nicely above),  and then 
2. Account for the fact that all deployments in years k+2, k+3, ... now happen one year earlier, by applying the corresponding time sensitivities (this accounts for changes in costs, and in technical efficiencies, through time.)

**Comment by jia-chenhua** [comment]
Following https://github.com/rangl-labs/netzerotc/issues/13#issuecomment-915934273, after using $`\frac{ \partial r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}}_k, \chi^{\mathrm{op}}_k, r^{\mathrm{rev}}_k) }{ \partial \chi^{\mathrm{cap}}_k } \approx \frac{ r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}}_k+\Delta, \chi^{\mathrm{op}}_k, r^{\mathrm{rev}}_k) - r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}}_k, \chi^{\mathrm{op}}_k, r^{\mathrm{rev}}_k) }{ \sum \Delta }`$ to calculate the approximated $`r^{\mathrm{eco}}_k (\chi^{\mathrm{cap}}_k+\Delta \chi^{\mathrm{cap}}_k, \chi^{\mathrm{op}}_k, r^{\mathrm{rev}}_k):=\hat{r^{\mathrm{eco}}}_k`$, where the $`\Delta \chi^{\mathrm{cap}}_k`$ is the **_actual change of total capex_** of year $`k`$, and the $`\hat{r}_k`$ for size-changed (small $`\Delta=100`$ for actionable technology's capex) reward is used to distinguish from $`\widetilde{r}_k`$ for 1-year time-shifted reward as in https://github.com/rangl-labs/netzerotc/issues/13#issue-987617048, this size-changed $`\hat{r}_k`$ has to be mapped back to `state.step_count` year using the product of sensitivities from year `state.step_count` to year $`k-1`$. This double-operation will account for the both the size and time sensitivities listed in https://github.com/rangl-labs/netzerotc/issues/13#issuecomment-915934273.

To explain this using an example, first we need to clarify the indexing of years in the `env.py`: in the following diagram for `state.step_count=0` in the `env.py`:
![image](https://user-images.githubusercontent.com/89832509/132889494-b66d5f0b-7ba9-4d40-8151-3cf0ec3326fb.png)

**Comment by jia-chenhua** [comment]
For test running using https://github.com/rangl-labs/netzerotc/blob/master/environment/test_reference_environment.py:

To test whether jobs and economic impact are correctly changed/calculated using size sensitivity/derivative w.r.t. capex:

first uncomment https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L150 and https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L151 so that the actual change of total capex is manually set to 200 (it can be set to 300 in these 2 lines later to test year 2031 to 2050), and then comment out https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L35, then run the codes https://github.com/rangl-labs/netzerotc/blob/master/environment/test_reference_environment.py up to https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L61 inclusive, and finally run https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L93.

Now go to https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L150 and https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L151, and change to 200 to 300, and re-run the codes https://github.com/rangl-labs/netzerotc/blob/master/environment/test_reference_environment.py up to https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L61 inclusive, and finally run https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L99 to test whether jobs and economic impact from year 2031 to 2050 are correct.


Now, to test whether the action of 1 year shifting at the beginning/1st step will give the correct results saved in the xlsx files:

First go back to comment out lines https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L150 and https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/reference_environment/env.py#L151, and then comment out https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L33, then run the codes https://github.com/rangl-labs/netzerotc/blob/master/environment/test_reference_environment.py up to https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L88 inclusive, and this will check if the 1 year shifting time sensitivity calculations are correct.

The comments from https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L64 to https://github.com/rangl-labs/netzerotc/blob/8200160c5b5607bf9387abe3dd2787989b6809ef/environment/test_reference_environment.py#L86 may be helpful for the testing.

**Comment by moriartyjm** [comment]
This approach is on hold, as we have successfully compiled the spreadsheets to Python
