### ISSUE TITLE
Prepare challenge documentation (11 Oct)

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#21]
- [x] Update READMEs in GitHub
- [x] Create text for EvalAI tabs
- [x] Deploy text into EvalAI tabs
- [x] Create code samples and submission tutorial (see #25 )

**Comment by moriartyjm** [comment]
Google doc containing text for EvalAI:

[https://docs.google.com/document/d/1Y1yP2itim5aB7MPLORHP8kROt4mgNVZ5rStFseTrnmk/edit?usp=sharing](url)

**Comment by masonlr** [comment]
"Deploy text into EvalAI tabs" is now complete as part of #39.

**Comment by masonlr** [comment]
See https://github.com/rangl-labs/netzerotc/pull/39#issuecomment-939641077
