### ISSUE TITLE
Prepare platform (18 Oct)

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#25]
Deploy platform in Azure specified for 50 teams and Slack channel.

The component tasks are:

- [x] Create dedicated AWS container registry for NZTC challenge
- [x] End-to-end test of latest environment container using testing VM
- [x] Stress test of challenge using scripting to deploy 20-30 simultaneous evaluation processes. Results will guide  Azure VM sizing.
- [x] Creation of links from a subdomain, such as challenges.rangl.org, to the production challenge
- [x] Creation of challenge documentation website and linking to rangl.org
    - [x] Documentation will include code samples and a tutorial on the challenge submission process

**Comment by masonlr** [comment]
Have tested 10 simultaneous submissions using a shell script:

```shell
#!/bin/bash

for i in $(seq 10); do
    evalai push submission:v0.1.0 --phase nztc-dev-8 &
done
```

There is a queuing system built into the evalai backend, so this test didn't overload the backend, as there is a maximum number of concurrent evaluations – which likely can be configured.
