### ISSUE TITLE
Adopt direct control of deployment

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#30]
- [x] Add loading and saving of Python-compiled spreadsheets (depends on #31 ): dealt with in #34 
- [x] Confirm that CCUS is controlled implicitly by 'Pathways to net zero' spreadsheet, ensuring net zero by 2050 (through assumption that 100% of requirement is deployed in 2050) 
- [x] Add calculations for jobs to environment
- [x] Ensure that deployment rates have upper limits

**Comment by jia-chenhua** [comment]
This is the current upper limits of the deployment rates: https://github.com/rangl-labs/netzerotc/blob/ee3d439f1adddf3ff43734e454f0b62fd8ea4866/environment/reference_environment_direct_deployment/env.py#L123

And in https://github.com/rangl-labs/netzerotc/blob/ee3d439f1adddf3ff43734e454f0b62fd8ea4866/environment/reference_environment_direct_deployment/env.py#L137, the new deployment values are also clipped to the highest 2050 target among 3 scenarios, which is Storm's 2050 offshore wind, Breeze's 2050 blue hydrogen, Storm's 2050 green hydrogen (same as the upper limit of action space).

Let me know if the latter one is too restrictive if we can allow much higher deployment number than 2050's target.
