### ISSUE TITLE
Confirm whether 'Pathways to Net Zero - Simplified' spreadsheet needs to be hashed

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#31]
The environment now uses a simplified version of the 'Pathways to Net Zero' spreadsheet to generate rewards in each year.

- [ ] Confirm whether 'Pathways to Net Zero - Simplified.xlsx' can be uploaded to GitHub

**Comment by masonlr** [comment]
#35 is a minimal example of this. If we do need to serialise the Excel file, then it is possible.

**Comment by blairoconnornztc** [comment]
I will confirm with the owners in NZTC.

**Comment by blairoconnornztc** [comment]
I have confirmed with ORE Catapult that we can release the data onto Github with the requirement that all text and graphs etc be removed so that the data is in effective anonymised.

**Comment by moriartyjm** [comment]
We will anonymise as agreed
