### ISSUE TITLE
Create regular blog posts

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#32]
We would like to have two versions of the blog: one on our Turing project page (in standard Turing format) and one at RangL.org (which can be formatted more flexibly)

- [x] Create our own version of the blog at rangl.org

Create blog post for each workshop, to document [here](https://www.turing.ac.uk/research/research-projects/ai-control-problems) the process of building a challenge. Draft blog posts are available on Teams prior to publication.

 - [x] 21st June workshop
 - [x] 1st July
 - [x] 19th July
 - [x] 20th September
 - [x] 4th October
 - [x]  18th October
 - [x] 8th November
 - [x] 22nd November
 - [x] 6th December

**Comment by jmontalvo94** [comment]
File updated in Teams with blog posts of July 19 and September 20 workshops.

**Comment by r-saldanha** [comment]
Suggest relegating detailed blog posts to RangL site as suggested by @jmontalvo94 then listing in chronological order works. I would then make the Turing blog more "corporate", i.e. general in reverse chronological. [I don't want to merely invent work for others so happy to have a stab at re-writing Turing site myself if I can get (temporary) access to update.]

**Comment by moriartyjm** [comment]
> I would then make the Turing blog more "corporate", i.e. general in reverse chronological. [I don't want to merely invent work for others so happy to have a stab at re-writing Turing site myself if I can get (temporary) access to update.]

That would be great @r-saldanha. We don't have edit privileges to Turing websites unfortunately, but I've found that sending the text in an email to the web team usually works fine.

**Comment by moriartyjm** [comment]
Both the Turing and RangL.org blogs have now been updated and completed with the announcement of the winners on 1st March. Further entries can be added later, but closing this issue now. Many thanks @jmontalvo94 and @tomaszkosmala for your work on this!
