### ISSUE TITLE
Relative paths when importing Excel files

### ISSUE THREAD

**Issue by masonlr** [rangl-labs/netzerotc#33]
We need to use relative paths when importing resources:

For reference, from @jia-chenhua:
> And for the relative path issue, now in the env.py, it reads the Excel xlsx file using a relative path './compiled_workbook_objects/Pathways to Net Zero - Simplified.xlsx'. This is fine for testing using the 'test_reference_environment_direct_deployment.py' because this script is located in the \netzerotc\environment\ folder. However, when running the training and evaluation scripts train.py and evaluate.py, these scripts are in \netzerotc\local_agent_training_and_evaluation\ , so currently in these 2 scripts, I had to manually add os.chdir("../environment/") before creating the environment env = gym.make("reference_environment_direct_deployment:reference-environment-direct-deployment-v0") (this will read and compile the Excel workbook) and add os.chdir("../local_agent_training_and_evaluation/") after it to switch back to training and evaluation scripts own directory. This approach is only an ad hoc solution, and John would like to use some package to get the absolute Git path and use this path inside the env.py. I tried the gitpython package and use import git  at the beginning, but the import git doesn't work if I don't have git executable installed, since I use a portable git GUI without git installed, so I didn't use the git executable. So please let me know if you have simpler solution without using the gitpython package but also able to get the absolute path so that the training and evaluation scripts can be run in their own folder without switching to other ones.

**Comment by masonlr** [comment]
This will be fixed by https://github.com/rangl-labs/netzerotc/pull/34

**Comment by masonlr** [comment]
We can rely on python itself to do this instead of adding more complexity.

Flip the problem and let the environment figure out its own location. You can rely on the in-built `__file__` variable to do this:

```python
p = Path(__file__)

# determine the relative path to the workbooks directory
workbooks = p.resolve().parent.parent / "compiled_workbook_objects"
sensitivities = p.resolve().parent.parent / "sensitivities"
```

**Comment by masonlr** [comment]
> while also needing to implement #36 and #5

I can see there's a revert commit here https://github.com/rangl-labs/netzerotc/pull/34/commits/17aa28bd11c0c5525826c4426dca83e50025f572

Let me know if there are still any issues. Apologies I should have consulted with you, and just assumed that this would be tolerable. Black is a de facto standard for python these days – so you will see resistance whenever it's not used. We can apply black once you've got your changes in.

I suggest that we create pull requests for each stream of work – at the moment we only have pull request #34. 

It's perfectly okay to address multiple issues with one pull request.

At the moment if we look at #36 or #5, there is no clear way to see where the work is being done. We want to have a situation where we can click on an issue, then see a link to the relevant pull request that is implementing the content.

**Comment by jia-chenhua** [comment]
Hi @masonlr , sorry for the delay in response. I had very limited previous experience of using git/GitHub before (probably only the 3 very basic operations: pull, commit, push), so I didn't know it was so easy to revert a specific commit while keeping other commits retained or even untouched, especially in a nice git GUI (like https://github.com/gitextensions/gitextensions). 

And yes, let's apply black formatter later when there is no significant change or further implementation is needed. In fact, the major complaint that I have with the black formatter is that, it blindly format everything without too much control over it, and for lines like `Pathways2Net0ColumnInds = np.array(['P','Q','R','S','T','U','V','W','X','Y','Z','AA','AB','AC','AD','AE','AF','AG','AH','AI'])` in the `env.py`, the black formatter will make every single string/character occupy one line, which is not only wasting the very limited code editor's space inside Spyder IDE, but also makes mouse scrolling navigation in code editor of Spyder IDE much more inconvenient/inefficient, unless I change my mouse scrolling's number of lines per notch of mouse wheel to a much larger number globally in my OS, which will affect my using of other software. So if there is some way to "protect" some lines of code to be not blindly formatted by black formatter, then I think I should be fine with it. But again, we can do that later.

Regarding the pull request, should we create another "fast development/implementation/issue fixing" branch based on the `direct_action_on_deployment` branch, and then frequently merge small or every single change to this `direct_action_on_deployment` branch? Or should we work on the `direct_action_on_deployment` branch, but frequently create merge request to merge the changes to the main/master branch? (Sorry, I'm still a newcomer to GitHub's branch management/pull requests, so apologies for not being able to respond to your request of creating more pull request earlier, while keeping pushing new commits during the course of implementing new things or fixing the issues).

**Comment by masonlr** [comment]
> it blindly formats everything without too much control over it

This is the main reason that black exists. It is opinionated.  😏 

> the black formatter will make every single string/character occupy one line

This is hinting that there could be higher-level issues with the setup. For example, it might be hinting that the array shouldn't be written in-line here and should be in a config variable elsewhere in the code, or read in from a config file. It might be hinting that variable names are too long. There are other benefits, for example, in terms of testing and interactive iteration, where you can comment out a single element in the array – this is not possible when it's in-line. Here, the black formatting is what's called "stable under refactoring" – it's designed so that the git diff statements are easy to read (which is important when collaborating), not necessarily to use the smallest number of editor lines.

> Regarding the pull request

Branches represent units of work. Ideally these should be very limited in scope and remain open for less than one week. This means that branches should be short lived and the only reliable surviving branch is `main`. Branches are "cheap" in git, so there is no problem with having several branches open at one time – as long as they are short lived.

>  but frequently create merge request

Once you think it's in a good enough state, we need to merge `direct_action_on_deployment` into `main` and immediately _delete_ `direct_action_on_deployment`. If there are more items that haven't been finished, capture them in an issue and start working on them on a new branch based on the newly updated `main` branch. Communicate what is going on using a new pull request.

> Sorry, I'm still a newcomer to GitHub's branch

No worries. There are lots of different ways that projects do this, so it's not always clear.

One of the simplest explanations is here: https://guides.github.com/introduction/flow/
