### ISSUE TITLE
Confirm round trip with EvalAI infrastructure

### ISSUE THREAD

**Issue by masonlr** [rangl-labs/netzerotc#40]
Now that #38 ensures that the environment is working with containerisation, we need to test a round trip with the full EvalAI infrastructure.

This issue contributes to #25.

**Comment by moriartyjm** [comment]
Do these phases perhaps need to be approved in the Django backend?

**Comment by tomaszkosmala** [comment]
Yes, I had. It worked after reseting evalai, as described in #39 .
