### ISSUE TITLE
Add noise to scenarios

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#5]
To do:

- [x] Add forecasts to environment state and observation space
- [x] Add noise to model (carbon price and capex, opex, devex costs of offshore wind, blue and green hydrogen, CCUS)
- [x] Elaborate IEV to include annual carbon emissions
- [x] Agree economic approach to accounting for emissions (see #6 )
- [x] Agree other factors to be randomised (eg. cost reduction curves)

Currently the problem is deterministic. Adding random noise to the scenarios would both reflect real-world uncertainty and increase the challenge difficulty.

From discussion during Workshop 2, the most volatile input may be the price of carbon. If the IEV models the annual carbon output then the environment can convert this to a noisy carbon cost at each step. Also, it then becomes natural to include expert predictions for the carbon price in the environment state and observation space.

Adding noise to the construction and/or procurement process was also discussed.

**Comment by tomquinn-orec** [comment]
Pathways to Net Zero file has been expanded to model carbon bills for each scenario. Under the CCUS tab, there is a forecast carbon price set at £85/tonne (real), equivalent to EUR100. 
For each scenario, I've calculated a total carbon price - which is effectively assuming the price is paid for generating emissions, and not dependent on what happens to the carbon. I've also calculated the carbon price for emissions. CCUS capacity is modelled to increase to be able to capture 100% of emissions in 2050, but from a slow start, so we model varying amounts of carbon emitted to the atmosphere. This trends to 0 as CCUS capacity ramps up.

**Comment by dindjic** [comment]
The noise can be "coloured": if there any composite leading indicators for jobs or sectors, we can incorporate their dynamics.

**Comment by moriartyjm** [comment]
Agreed that it makes sense to randomise future cost reduction curves

**Comment by moriartyjm** [comment]
Here's an example result from training on the randomised environment
https://github.com/rangl-labs/netzerotc/blob/direct_action_on_deployment/environment/MODEL_8_10models_100episodes_DirectDeploymentRandomized.png

**Comment by moriartyjm** [comment]
@jia-chenhua, the approach to adding noise looks good. Closing! :tada:
