### ISSUE TITLE
Add features to help with calibration

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#52]
The following subtasks should help us calibrate the environment:

- [x] Add `breeze_agent`, `gale_agent` and `storm_agent` to `util.py`
- [x] Add legends to plots (including the top-right plot)
- [x] Add yearly CO2 emissions in the top-left plot ('CCUS' tab, row 63)
- [x] Train an RL agent under 100x increased carbon cost (and verify that blue hydrogen is not then an optimal choice)
- [x] Investigate why the jobs number appears to go negative in 2050

**Comment by jia-chenhua** [comment]
![MODEL_9_eval_on_deterministic](https://user-images.githubusercontent.com/89832509/139655253-28b44acd-9008-473d-b50b-e86ba6c7a76c.png)
