### ISSUE TITLE
Confirm reward formula

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#6]
- [x] Consider whether there are clear arguments for opex/capex/revenue cost variations to be correlated, and/or correlated across different technologies: Decided to maintain constant ratios between: (i) blue and green hydrogen price, (ii) CCUS revenue and carbon price
- [x] Confirm whether rewards need to have yearly discounting applied: Decided that rewards are flat cash (no discounting)
- [x] Confirm relationship between blue hydrogen gas feedstock price (currently 20 / MWh) and hydrogen price (40) if gas price rises steeply, and their relationship to the natural gas cost (6.84/TWh): decided that (i) `hydrogen price = blue hydrogen gas feedstock price + 20` and (ii) the ratio `blue hydrogen gas feedstock price / natural gas cost` would be held constant 
- [x] Formula for rewards 
- [x] Agree whether agent uses scenarios, or controls deployment directly
- [x] Agree whether job numbers can be simply approximated (eg. from total costs)

Reinforcement learning algorithms learn which actions maximise long-run rewards. Our choice (or choices) of reward are therefore important to guide the challenge (or challenges) toward the desired kinds of pathway to net zero. In particular, modelling should internalise all factors which are to be considered. 

The IEV models the following components of reward:
* Capex
* Opex
* Jobs
* Revenue
* Decomm (Decommissioning costs)

We have added modelling of the following to the IEV:
* Emissions

Possibilities are:
1. Reward = economic impact - emissions
2. Reward = - cost of solution - emissions

Option 1 seems to give trivial solutions (see #16).

If a suitable reward formula cannot be found with the current setup, we may consider decoupling from the three scenarios and allowing the agent to directly control the deployment of offshore wind, blue hydrogen and green hydrogen. This is likely to require direct calculation of the rewards from deployment levels, which appears relatively straightforward for costs and emissions, although the calculation of jobs may require an approximation

**Comment by tomquinn-orec** [comment]
The crux of the problem is that cost reduction is good (cheaper energy) but reduced spending is bad (fewer jobs). 
At the moment we use a fixed labour/cost ratio, so assuming that for e.g. offshore wind 25% of spending is on direct labour across the whole model period. A potential fix is to assume that as costs reduce, jobs also reduce but not at the same rate - so a 10% drop in costs may only lead to a 5% drop in labour cost - so over time the labour/cost ratios increase. Not sure how adaptable that will be, or how true! 
It is possible that we can estimate the value/reward of cheaper energy, and see if it outpaces the value of job losses? The problem is that by measuring jobs as direct and indirect, a cut in spending leads to fewer direct jobs and fewer indirect jobs, so it is a multiplying effect.

**Comment by moriartyjm** [comment]
Great to see that the IEV has been updated to include emissions costs.

To preserve jobs numbers, we have discussed the option of using constraints rather than rewards - eg minimum total number of jobs, maximum rate of job reductions over 1 / 2 / 3 years, etc. So this doesn't necessarily have to be solved by the choice of reward.

Re costs, my understanding is that higher total economic impact actually means higher costs (if economic impact = Capex + Opex + Decomm + Revenue). So if we try to maximise this while minimising emissions, the winning strategy is likely to be Storm, but accelerated as much as possible -- since this probably both maximises costs (and also jobs) and minimises emissions. So the challenge might be too easy if the goal is to maximise (economic impact - emissions).

Another idea may be to maximise the return from the energy sector (specifically), with emissions costs internalised? That is, to maximise

Revenue - (Capex + Opex + Decomm + Emissions)

subject to constraints on jobs (total level and/or rate of change over various horizons). Thoughts welcome!

**Comment by dindjic** [comment]
[https://netzeroamerica.princeton.edu/](url) IEV team to confirm the similarities.

**Comment by tomquinn-orec** [comment]
Hydrogen revenue calculations:

Green hydrogen - levelised cost of hydrogen (capex & opex) but not including electricity price. 
Blue hydrogen - fixed cost of blue H2 production, not including gas feedstock price. 

So both are effectively the fixed costs, as we didn't want to double count economic benefit of electricity produced in offshore wind, and then count it again in green H2 revenue. Same for blue H2 and gas. 

From a gas markets perspective, it would be interesting to value the cost of gas imports, and impact on blue h2 prices. This isn't going to feed through to the reward calculation as the model is currently set up.
