### ISSUE TITLE
Deployment plan for training virtual machines (non-urgent)

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#67]
A plan to facilitate the 'lean RL' competition phase described in #66 using our allocated Azure resource

**Comment by dindjic** [comment]
Earlier today @moriartyjm mentioned testing "long" training sessions, like a week. The cost of running cloud is internalised. On the other hand  it offers an alternative monetisation or sponsorship avenue as certain private AI clouds show.
![image](https://user-images.githubusercontent.com/3080587/145820778-adab41ad-28f7-4572-ad6e-47badc81b798.png)
