### ISSUE TITLE
Decide where to advertise challenge

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#74]
We can already start advertising - since this takes time (eg getting into monthly newsletters etc). 

- [x] Draft advert text via Slack. To include: Dates, link to rangl.org - RS&DI?
- [x] Update challenge overview at EvalAI to reflect recent work on the environment & evaluation criteria - JM&TK
- [x] Share with NZTC & ORE - JM

Places to advertise with assignees:

- [x] Turing newsletter - JM
- [x] https://www.climatechange.ai ; Open Energy Modelling Initiative ; Google Group - MachineLearning.org - JMA
- [ ] LinkedIn & Twitter - RS&DI
- [x] https://openclimatefix.org - LM
- [x] Applied probability mailing lists - TK
- [x] ResearchGate / Physics mailing lists - JH
- [x] RangL.org mailing list - JM

**Comment by r-saldanha** [comment]
- [ ] https://www.planetmark.com/ – RS

**Comment by moriartyjm** [comment]
Hello all, here's an advert text:

**Reinforcement Learning Challenge, 17th-31st January 2022**

The Net Zero Technology Centre, Alan Turing Institute RangL project and Oxquant announce the ‘[Pathways to Net Zero](https://rangl.org)’ Reinforcement Learning challenge, which will take place from 17th-31st January 2022. 

As showcased at COP26 (see the video [here](https://vimeo.com/632748761)), the challenge is to control the rate of deployment of zero-carbon technologies towards net zero UK carbon emissions in 2050. Sign up [here](https://docs.google.com/forms/d/e/1FAIpQLSdyFCd55fPasdq-30GQ1Hl4m_L5GgTULZ0WWO0GCLbiyKx8ag/viewform) to compete as an individual or team.

**Comment by jia-chenhua** [comment]
ResearchGate discussions/questions (low visibility; a ResearchGate user needs to login to see this in their feed): https://www.researchgate.net/search/question?q=Reinforcement+Learning+Challenge%2C+17th-31st+January+2022

LinkedIn event: https://www.linkedin.com/events/reinforcementlearningchallenge-6873442667838156800/
(Please add me to your linked in network and advertise it)
