### ISSUE TITLE
Test submission of trained agent

### ISSUE THREAD

**Issue by moriartyjm** [rangl-labs/netzerotc#97]
We want to check that trained agents are submitting and evaluating properly to EvalAI (as they are more complex than random or rule-based agents).
- [x] Train agent, save, and submit to open loop  phase
- [x] Train agent, save, and submit to closed loop  phase
- [x] Check that evaluation results from trained agent are approximately equal on local machine and on EvalAI

**Comment by masonlr** [comment]
This has been completed.
